// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

// 注意：这里不再声明 allprojects 或 subprojects 仓库，因为已经在 settings.gradle 中管理